"""One-shot in-place editor for notebooks-v2/23_rank_effects.ipynb.

Adds the K-cellsplit Key Claims section + a cellsplit analysis cell.
Idempotent — re-running over the already-edited notebook is a no-op
(both insertions are sentinel-guarded).

Sources its numerics from scripts/output/nb23_cellsplit_rank/summary.json
(written by compute_nb23_cellsplit_rank.py).

Run:
    .venv/bin/python scripts/_apply_nb23_cellsplit_edits.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NB_PATH = ROOT / "notebooks-v2/23_rank_effects.ipynb"
SUMMARY_PATH = ROOT / "scripts/output/nb23_cellsplit_rank/summary.json"

SENTINEL_KC = "### Cellsplit-attribution K-IDs"
SENTINEL_CODE = "# ── Cellsplit rank effects (within dd_top carousel) ──"


def main() -> None:
    nb = json.loads(NB_PATH.read_text())
    summary = json.loads(SUMMARY_PATH.read_text())

    # ── Build the Key Claims K-cellsplit block ───────────────────────────
    rows = summary["by_cell"]
    n_with_cells = summary["n_trials_with_cells"]
    n_total = summary["n_trials_in_substrate"]
    modal = summary["modal_n_cells"]
    n_carousel_clicks = summary["n_trials_with_carousel_click"]
    sp = summary["spearman_vs_cell_position"]

    def fmt_rho(d):
        if not d:
            return "—"
        rho, p = d["rho"], d["p"]
        p_s = "< 10⁻⁶" if p < 1e-6 else f"{p:.3g}"
        return f"**{rho:+.3f}**, p = {p_s}"

    kc_lines = [
        "",
        "### Cellsplit-attribution K-IDs (within-carousel rank, dd_top stratum)",
        "",
        f"*Population: {n_with_cells} / {n_total} dd_top-topped trials "
        f"with cell-aware AOI snapshots (modal carousel size = {modal} cells). "
        f"Source: `scripts/output/nb23_cellsplit_rank/summary.json` "
        f"(generated by `compute_nb23_cellsplit_rank.py`).*",
        "",
        "Cellsplit rank decomposes the dd_top widget — which collapses to "
        "rank-0 under all three other flavors — into K per-cell rank "
        "positions. The same monotone-with-rank story replicates *within "
        "the carousel*, mirroring the organic-rank gradient.",
        "",
        "| ID | Measure | Value |",
        "|---|---|---|",
        f"| **K-cellsplit-1** | CTR by cell position ρ "
        f"(cells 1–{rows[-1]['cell_position']}) "
        f"| {fmt_rho(sp.get('ctr'))} |",
        f"| **K-cellsplit-2** | Mean fixation count by cell position ρ "
        f"| {fmt_rho(sp.get('mean_fix_count'))} |",
        f"| **K-cellsplit-3** | Mean dwell time by cell position ρ "
        f"| {fmt_rho(sp.get('mean_dwell_ms'))} |",
        f"| **K-cellsplit-4** | Carousel CTR (cell 1) | "
        f"**{rows[0]['ctr']*100:.2f}%** ({rows[0]['n_clicks_in_cell']} / "
        f"{rows[0]['n_trials_with_cell']:,}) |",
        f"| **K-cellsplit-5** | Carousel CTR drop, cell 1 → cell 4 | "
        f"**{rows[0]['ctr']*100:.2f}% → "
        f"{rows[3]['ctr']*100:.2f}%** "
        f"({(rows[3]['ctr']/rows[0]['ctr']-1)*100:+.1f}% relative) |",
        f"| **K-cellsplit-6** | Trials with any carousel click | "
        f"**{n_carousel_clicks:,}** ({n_carousel_clicks/n_with_cells*100:.1f}% of dd_top trials) |",
        "",
        "**Per-cell rank table** (cells 1 = leftmost, K = rightmost):",
        "",
        "| cell | n_trials | n_clicks | CTR | mean fix count | mean dwell (ms) |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        kc_lines.append(
            f"| {r['cell_position']} | {r['n_trials_with_cell']:,} | "
            f"{r['n_clicks_in_cell']} | {r['ctr']*100:.2f}% | "
            f"{r['mean_fix_count']:.2f} | {r['mean_dwell_ms']:.0f} |"
        )
    kc_lines.extend([
        "",
        "> **Within-carousel rank effect is real and monotone.** The same "
        "*declining attention with rank* gradient that defines the "
        "organic-rank story (K18–K28, K-bbox-*) holds *inside* the dd_top "
        "carousel. The cell-1-vs-cell-4 CTR drop (4.33% → 3.18%) is "
        "directionally consistent with rank-1-vs-rank-4 CTR among organic "
        "results — and falsifies the implicit assumption that dd_top is a "
        "single attentional unit.",
        ">",
        "> **Caveat — LF/HF not yet computed at cellsplit grain.** The "
        "existing butterworth-lfhf-by-position.json is keyed by absolute "
        "rank. Re-derivation for cellsplit is deferred to a v2 pass.",
        "",
        "---",
        "",
    ])
    cellsplit_block = "\n".join(kc_lines)

    # ── Insert into Key Claims markdown (cell 1) ─────────────────────────
    kc_src = nb["cells"][1]["source"]
    if isinstance(kc_src, list):
        kc_src = "".join(kc_src)

    if SENTINEL_KC in kc_src:
        # Replace previously-inserted block (idempotent re-run).
        start = kc_src.index(SENTINEL_KC) - 1  # leading newline
        # Find the next "---" separator after our block to bound the replacement
        end_marker = "\n---\n\n"
        end_idx = kc_src.find(end_marker, start)
        if end_idx == -1:
            end = len(kc_src)
        else:
            end = end_idx + len(end_marker)
        kc_src = kc_src[:start] + cellsplit_block + kc_src[end:]
        action_kc = "replaced existing K-cellsplit section"
    else:
        # First-time insertion: place AFTER the K-bbox table, BEFORE the
        # legacy K-IDs separator.
        anchor = ("> **Bbox attribution is the recommended primary for "
                  "paper figures.**")
        if anchor in kc_src:
            # Place after the paragraph containing the anchor — find the
            # next "---" separator after the anchor.
            anchor_pos = kc_src.index(anchor)
            sep = "\n\n---\n\n"
            sep_pos = kc_src.find(sep, anchor_pos)
            if sep_pos == -1:
                raise RuntimeError("could not locate insertion point")
            insert_at = sep_pos + len(sep)
            kc_src = kc_src[:insert_at] + cellsplit_block + kc_src[insert_at:]
            action_kc = "inserted K-cellsplit section after bbox primary block"
        else:
            raise RuntimeError("anchor not found; manual insertion required")

    # Also update the flavors-coexist header to declare four.
    three_note = ("*Notebook: `23_rank_effects.ipynb`. Three rank flavors now coexist:*")
    four_note = ("*Notebook: `23_rank_effects.ipynb`. Four rank flavors now coexist:*")
    if three_note in kc_src:
        kc_src = kc_src.replace(three_note, four_note)
    # Add the cellsplit bullet to the flavor list if not present.
    bbox_bullet = ("- **Organic-bbox rank** (K-bbox section below, CV-extracted "
                   "visible cards, pixel-accurate) — primary")
    bbox_bullet_v2 = ("- **Organic-bbox rank** (K-bbox section below, CV-extracted "
                      "visible cards, pixel-accurate) — primary for organic-page slots")
    cell_bullet = ("\n- **Cellsplit rank** (K-cellsplit section below, per-cell "
                   "positions within dd_top carousel) — primary for within-carousel slots")
    if bbox_bullet in kc_src and cell_bullet not in kc_src:
        kc_src = kc_src.replace(bbox_bullet, bbox_bullet_v2 + cell_bullet)

    nb["cells"][1]["source"] = kc_src

    # ── Insert/replace the cellsplit analysis code cell ─────────────────
    code_src = f"""{SENTINEL_CODE}
# Loads summary.json from compute_nb23_cellsplit_rank.py and renders a
# three-panel small-multiples figure: CTR / mean fixation count / mean
# dwell, all vs cell position. Mirrors §5's unified-view structure
# applied at the within-dd_top grain.

import json
from pathlib import Path
import matplotlib.pyplot as plt

CS_SUMMARY = Path('../scripts/output/nb23_cellsplit_rank/summary.json')
cs = json.load(open(CS_SUMMARY))
rows = cs['by_cell']
cells = [r['cell_position'] for r in rows]
ctr = [r['ctr'] * 100 for r in rows]
mean_fix = [r['mean_fix_count'] for r in rows]
mean_dwell = [r['mean_dwell_ms'] / 1000 for r in rows]
ntrials = [r['n_trials_with_cell'] for r in rows]

sp = cs['spearman_vs_cell_position']
fig, axes = plt.subplots(1, 3, figsize=(13, 4.2))

panels = [
    ('CTR (% of trials with cell)', ctr, '#0072B2', sp.get('ctr', {{}}), '%'),
    ('Mean fixation count', mean_fix, '#E69F00', sp.get('mean_fix_count', {{}}), ''),
    ('Mean dwell (s)', mean_dwell, '#009E73', sp.get('mean_dwell_ms', {{}}), 's'),
]
for ax, (title, ys, color, rho, unit) in zip(axes, panels):
    ax.bar(cells, ys, color=color, edgecolor='#222222', linewidth=0.9, width=0.7)
    ax.set_title(title, fontsize=12, weight='bold')
    ax.set_xlabel('cell position (1 = leftmost)', fontsize=10)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    for x, y, n in zip(cells, ys, ntrials):
        ax.text(x, y, f'n={{n:,}}', ha='center', va='bottom',
                fontsize=8, color='#444444')
    if rho:
        ax.text(0.97, 0.95,
                f'ρ = {{rho["rho"]:+.3f}}\\np = {{rho["p"]:.2g}}',
                transform=ax.transAxes, ha='right', va='top',
                fontsize=10, family='monospace', color='#222222',
                bbox=dict(boxstyle='round,pad=0.4',
                          facecolor='#fdf8f2', edgecolor=color, linewidth=1))

fig.suptitle(
    f'Within-carousel rank effect on the dd_top stratum  ·  '
    f'{{cs["n_trials_with_cells"]:,}} trials  ·  '
    f'modal {{cs["modal_n_cells"]}}-cell carousel',
    fontsize=13.5, weight='bold', y=1.02,
)
plt.tight_layout()
plt.show()
"""

    new_md = (
        "## Cellsplit rank: within-carousel rank effects\n\n"
        "The three rank flavors above (absolute / organic-h3 / organic-bbox) "
        "all collapse the dd_top carousel to a single attentional unit at "
        "rank 0. **Cellsplit rank** resolves dd_top into its K constituent "
        "cells, exposing a within-carousel rank effect that mirrors the "
        "organic-rank gradient.\n\n"
        "Restricted to the 1,581 dd_top-topped trials. Source: "
        "`compute_nb23_cellsplit_rank.py` → "
        "`scripts/output/nb23_cellsplit_rank/summary.json`. Detailed "
        "K-cellsplit Key Claims in the block at the top of this notebook."
    )

    # Find insertion point: after the existing "summary table" md cell (last md).
    # Cleanly: append the new section just before the last cell if it's md,
    # else append at end.
    found_existing = False
    for i, c in enumerate(nb["cells"]):
        src = c.get("source", "")
        if isinstance(src, list):
            src = "".join(src)
        if c.get("cell_type") == "code" and SENTINEL_CODE in src:
            # Already inserted — update in place
            c["source"] = code_src
            found_existing = True
            action_code = f"replaced existing cellsplit cell at index {i}"
            break

    if not found_existing:
        new_md_cell = {
            "cell_type": "markdown",
            "metadata": {},
            "source": new_md,
        }
        new_code_cell = {
            "cell_type": "code",
            "metadata": {},
            "execution_count": None,
            "outputs": [],
            "source": code_src,
        }
        # Insert before the "Summary table" cell (last md cell in default layout)
        insert_idx = len(nb["cells"])
        for i, c in enumerate(nb["cells"]):
            src = c.get("source", "")
            if isinstance(src, list):
                src = "".join(src)
            if c.get("cell_type") == "markdown" and src.lstrip().startswith(
                "## Summary table"
            ):
                insert_idx = i
                break
        nb["cells"][insert_idx:insert_idx] = [new_md_cell, new_code_cell]
        action_code = (
            f"inserted cellsplit md + code cells at index {insert_idx}-{insert_idx+1}"
        )

    NB_PATH.write_text(json.dumps(nb, indent=1) + "\n")
    print(f"[ok] {action_kc}")
    print(f"[ok] {action_code}")
    print(f"[ok] notebook written: {NB_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
